import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "About",
  description:
    "Why this meeting planner exists, who built it, and how it stays useful for distributed teams.",
};

export default function AboutPage() {
  return (
    <div className="bg-background min-h-dvh font-sans">
      <main className="mx-auto flex max-w-2xl flex-col gap-6 px-4 py-12 sm:py-20">
        <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">
          About this site
        </h1>
        <p>
          This is a small, opinionated meeting planner built for people who
          actually work across time zones — distributed engineering teams,
          digital nomads, agencies serving global clients, and freelancers
          coordinating with clients on three continents.
        </p>
        <p>
          The big legacy timezone sites are powerful but feel built for 2008.
          The mobile experience is rough, the workflow is &quot;convert one
          time&quot; rather than &quot;plan a recurring meeting,&quot; and the
          UI hasn&apos;t aged well. We wanted something modern, mobile-first,
          and biased toward the actual job-to-be-done: pick a time that respects
          everyone&apos;s working hours and copy a calendar invite or share
          link.
        </p>
        <h2 className="mt-4 text-xl font-semibold">What you&apos;ll find</h2>
        <ul className="list-disc space-y-1 pl-5">
          <li>
            A draggable multi-city timeline (up to five cities) on the{" "}
            <Link href="/" className="text-primary hover:underline">
              home page
            </Link>
            .
          </li>
          <li>
            <Link
              href="/meet/new-york-and-london"
              className="text-primary hover:underline"
            >
              City-pair pages
            </Link>{" "}
            with overlap windows, suggested meeting times, and DST notes for
            every two-city combination among 50 cities.
          </li>
          <li>
            <Link
              href="/city/lisbon"
              className="text-primary hover:underline"
            >
              Single-city guides
            </Link>{" "}
            with offsets to major cities and remote-work context.
          </li>
          <li>
            Concise explainers for the most common timezone abbreviations —{" "}
            <Link href="/timezone/pst" className="text-primary hover:underline">
              PST
            </Link>
            ,{" "}
            <Link href="/timezone/cet" className="text-primary hover:underline">
              CET
            </Link>
            ,{" "}
            <Link href="/timezone/jst" className="text-primary hover:underline">
              JST
            </Link>
            , and others.
          </li>
        </ul>
        <h2 className="mt-4 text-xl font-semibold">How it&apos;s built</h2>
        <p>
          Static HTML generated by Next.js, served from Cloudflare&apos;s edge.
          Time math runs on luxon and the IANA timezone database — the same
          libraries calendar and operating-system vendors use. No tracking
          beyond basic usage analytics.
        </p>
        <h2 className="mt-4 text-xl font-semibold">Get in touch</h2>
        <p>
          Suggestions, bug reports, or requests for additional cities are
          welcome. See the{" "}
          <Link href="/contact" className="text-primary hover:underline">
            contact page
          </Link>
          .
        </p>
      </main>
    </div>
  );
}
